#!/bin/bash
################################################################################
##
## Script that logs the synchronization status in WR-devices and check that
## the servo state is "TRACK_PHASE"
##
## Authors:
##	- Felipe Torres González (torresfelipex1<AT>gmail.com)
##
## System requirements: sshpass
##
## GNU Lesser General Public License Usage
## This file may be used under the terms of the GNU Lesser
## General Public License version 2.1 as published by the Free Software
## Foundation and appearing in the file LICENSE.LGPL included in the
## packaging of this file.  Please review the following information to
## ensure the GNU Lesser General Public License version 2.1 requirements
## will be met: http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html.
################################################################################

# How to interface with the WR device under test
CONN=ssh

# Etherbone variables
ETHBONE_DISCOVER=./bin/eb-discover
ETHBONE_DISCOVER_FLAGS=udp/

# Virtual UART Tool
VUART=./py7slib/shell.py

# Flag to enable sync check
SYNC=

# Temperature interval
TEMP=
# BUS used for external sensors
BUS="w1"
BUS_PATH=/sys/bus/$BUS/devices/
# DS18B20+ OneWire sensors have an unique address starting by 28
SENSOR_HADDR="28"
SENSORS=0

# Set the remote server (ip or name)
REMOTE="zen"
# Time interval to check the sync status (seconds)
INTERVAL="x"
# Remote username (in the WRZEN is 'root' & pass 'root')
REMOTE_USER='root'
REMOTE_PASS='root'

SSH_OPTIONS="-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o LogLevel=error"

TEST="/root/tools/zen/zen-vuart -c stat"

# File where the result of each check will be stored
LOG_FILE="x"

# The python tool to check the stat output
PYTOOL=./check_status.py

CHECK="x"

# Trap Ctrl-C and call ctrl_c() to end the test
trap ctrl_c INT

# -------------------------------------------

# Function to check if a device is alive
check_alive()
{
    if [ $VERBOSE_MSG != 0 ]; then
        echo -e "\033[1mChecking connection with $REMOTE_NAME ($REMOTE_ADDR)...\033[0m"
    fi
    ping -c 1 $1 &> /dev/null
    if [ $? -ne 0 ]; then
      echo -e "\e[31mCould not connect with $REMOTE_NAME($REMOTE_ADDR)\033[0m"
      exit 1
    fi
}

# -------------------------------------------

# Run the test using a ssh connection
runsshtest()
{
  echo -e "\033[1mChecking connection with $REMOTE...\033[0m"
  ping -c 1 $REMOTE &> /dev/null
  if [ $? -ne 0 ]; then
    echo -e "\e[31mCould not connect with $REMOTE\033[0m"
    exit 1
  fi
  echo -e "\033[1mRunning test in the remote WR-ZEN...\033[0m"
  stat=$(sshpass -p $REMOTE_PASS ssh $SSH_OPTIONS $REMOTE_USER@$REMOTE $TEST 2>&1)
  echo $stat >> temp

  if [ $LOG_FILE == "x" ]; then
    echo -e ">>> zen@$REMOTE -- $(date "+%H:%M:%S %d-%m-%Y")" 2>&1
    cat temp
  else
    echo -e ">>> zen@$REMOTE -- $(date "+%H:%M:%S %d-%m-%Y")" >> $LOG_FILE
    cat temp >> $LOG_FILE
  fi
  rm temp
}

# -------------------------------------------

# Run the test using an Etherbone connection
runethtest()
{
  echo -e "\033[1mChecking connection with $REMOTE...\033[0m"
  $ETHBONE_DISCOVER $ETHBONE_DISCOVER_FLAGS$REMOTE > temp
  size=$(cat temp | wc -l)
  if [ $size -lt 1 ]; then  # check the return code by eb-discover
    echo -e "\e[31mCould not connect with $REMOTE\033[0m"
    exit 1
  fi
  echo -e "\033[1mRunning test in the remote WR-LEN...\033[0m"
  echo "stat" > temp
  $VUART -i temp -o temp2 $REMOTE

  if [ $LOG_FILE == "x" ]; then
    echo -e ">>> len@$REMOTE -- $(date "+%H:%M:%S %d-%m-%Y")" 2>&1
    cat temp2
  else
    echo -e ">>> len@$REMOTE -- $(date "+%H:%M:%S %d-%m-%Y")" >> $LOG_FILE
    cat temp2 >> $LOG_FILE
  fi
  rm temp temp2
}

# -------------------------------------------

ctrl_c()
{
  # Called from ctrl-c
  if [ $CHECK == "x" ]; then
    CHECK_LOG=$LOG_FILE
  else
    if [[ $SYNC != "-s" && $TEMP != *"-t"* ]]; then
      echo -e "\033[31mYou must specify a checking argument: \033[1m-s or -t\033[0m"
      exit 3
    else
      CHECK_LOG=$CHECK
    fi
  fi
  # Check the raw log if it exists
  if [ -f $CHECK_LOG ]; then
    echo -e "\033[1mChecking the raw generated log...\033[0m"
    PYTOOL_FLAGS="$SYNC $TEMP $VERBOSE"
    $PYTOOL $CHECK_LOG $PYTOOL_FLAGS > temp
    if [ $? -gt 0 ]; then
      echo -e "\033[31mSome errors occured:\033[0m"
      cat temp
      rm temp
      exit 2
    else
      echo -e "\033[34mNo errors occured\033[0m"
      exit 0
    fi
  else
    echo -e "\033[1mNo LOG file to check, bye!\033[0m"
    exit 0
  fi
}

# -------------------------------------------

help()
{
cat << EOF
Usage: $(basename $0) [options]

Options:
-h|--help           Prints this help
-v|--verbose        Enables verbose mode
-r|--remote         Remote device (IP or name)
-i|--interval       Seconds between sync checking
-s|--sync           Enable synchronization checking
-t|--temp min,max   Enable temperature checking
-o|--output         Write output to file
-c|--check [log]    Only check a raw test log (bug: use in the last position)
-l|--conn opt       How to connect with the WR device
                    Options are:
                    · "ssh"     for WR-ZEN (linux)
                    · "ethbone" for WR-LEN (Etherbone)

EOF
exit 0
}


while [ $# -gt 0 ]; do # Until you run out of parameters . . .
  case "$1" in
    -h|--help) help;;
    -v|--verbose) VERBOSE="-v";;
    -r|--remote) REMOTE=$2;shift;;
    -i|--interval) INTERVAL=$2;shift;;
    -t|--temp) TEMP="-t $2";shift;;
    -s|--sync) SYNC="-s";;
    -o|--output) LOG_FILE=$2;shift;;
    -l|--conn) CONN=$2; shift;;
    -c|--check) CHECK=$2; ctrl_c $CHECK; shift;;
    *) echo "Unknown arg: $1"; help;;
  esac
  shift   # Check next set of parameters.
done

if [ $CONN == "ssh" ]; then
  echo -e "\033[1mRunning test over ssh\n\033[0m"
  if [ $INTERVAL != "x" ]; then
    while true
    do
      runsshtest
      sleep $INTERVAL
    done
  fi
  runsshtest
  ctrl_c
elif [ $CONN == "ethbone" ]; then
  echo -e "\033[1mRunning test over Etherbone\n\033[0m"
  if [ $INTERVAL != "x" ]; then
    while true
    do
      runethtest
      sleep $INTERVAL
    done
  fi
  runethtest
  ctrl_c
else
  echo -e "\033[31Invalid connection seleted, valid types are: ssh or eth\n\033[0m"
fi
